Update index.md
igorkamyshev/withease pull request #90
Opened 2024-08-07 13:10 UTC by Prokopchuk-Valentin

Дополнил в описании пару фраз и небольшой пример использования на react

2024-08-07 13:44 UTC, sergeysova commented on apps/website/docs/factories/index.md
> +  const counter = useStore($counter);
```suggestion
  const counter = useUnit($counter);
  const [onIncrement, onDecrement] = useUnit([increment, decrement])
```

2024-08-07 13:44 UTC, sergeysova commented on apps/website/docs/factories/index.md
> +We do not call `invoke` in components; instead, we call it in **`.js`** or **`.ts`** files, as if we were writing regular Effector code.
```suggestion
It is recommended not to call ⁠invoke within components; instead, it should be called in ⁠`.js` or ⁠`.ts` files, as if writing standard Effector code.
```

2024-08-07 13:44 UTC, sergeysova commented on apps/website/docs/factories/index.md
> +      <button onClick={() => decrement()}>Decrement</button>
```suggestion
      <button onClick={() => onIncrement()}>Increment</button>
      <button onClick={() => onDecrement()}>Decrement</button>
```

2024-08-07 17:12 UTC, Prokopchuk-Valentin commented on apps/website/docs/factories/index.md
> +  const counter = useStore($counter);
> Fixed, thanks!

2024-08-08 17:22 UTC, sergeysova approved these changes

2024-08-12 07:11 UTC, Prokopchuk-Valentin commented
@igorkamyshev, сможешь принять?

2024-08-15 05:41 UTC, igorkamyshev requested changes
Круто, спасибо!

Оставил пару минорных комментов 🙏

2024-08-15 05:41 UTC, igorkamyshev commented on apps/website/docs/factories/index.md
> +It is recommended not to call ⁠invoke within components; instead, it should be called in ⁠`.js` or ⁠`.ts` files, as if writing standard Effector code.
1. Предлагаю выделить предупреждение через `::: warning`
2. Предлагаю удалить упоминание `.js` или `.ts` файлов — это очень фреймворк специфик информация. Думаю, в примере ниже специфичном для Реакта это указать (`Now we can use`).

2024-08-15 05:41 UTC, igorkamyshev commented on apps/website/docs/factories/index.md
> +Now we can use `$counter`, `increment`, and `decrement` in our components
Давай добавим сюда коллапс-секцию с заголовком «например с Реактом это использовать можно так» или что-то такое. Хочется получить текст, который не будет акцентировать внимание на конкретном фреймворке.

2024-09-11 11:00 UTC, Prokopchuk-Valentin commented on apps/website/docs/factories/index.md
> +It is recommended not to call ⁠invoke within components; instead, it should be called in ⁠`.js` or ⁠`.ts` files, as if writing standard Effector code.
добавил

2024-09-11 11:00 UTC, Prokopchuk-Valentin commented on apps/website/docs/factories/index.md
> +Now we can use `$counter`, `increment`, and `decrement` in our components
добавил дополнительно vue, solid

2024-09-12 11:04 UTC, igorkamyshev requested changes
Примеры получились какие-то немножко не качественные. Если нет экспертизы написать для свелта корректный пример, давай его просто удалим и оставим реакт и вью 🙏

2024-09-12 11:04 UTC, igorkamyshev commented on apps/website/docs/factories/index.md
> +  import { useUnit } from 'effector-svelte';
Но ведь пакета `effector-svelte` не существует?..

2024-09-12 11:11 UTC, Prokopchuk-Valentin commented on apps/website/docs/factories/index.md
> +  import { useUnit } from 'effector-svelte';
удалил, да, по svelte ошибся

2024-09-12 11:12 UTC, merged